on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create local changes and commit
        run: |
          curl \
          -H "Accept: application/vnd.github.inertia-preview+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"\
          https://api.github.com/projects/12996588
